### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dhikacangin** [ggrievous/8muser#1]
C:\Users\Oke\Desktop\8muses downloader\8muser-master\app.py:39: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_driver_path, chrome_options=options)
Traceback (most recent call last):
  File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Oke\Desktop\8muses downloader\8muser-master\app.py", line 39, in <module>
    driver = webdriver.Chrome(chrome_driver_path, chrome_options=options)
  File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by dhikacangin** [comment]
> C:\Users\Oke\Desktop\8muses downloader\8muser-master\app.py:39: DeprecationWarning: use options instead of chrome_options
> driver = webdriver.Chrome(chrome_driver_path, chrome_options=options)
> Traceback (most recent call last):
> File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
> self.process = subprocess.Popen(cmd, env=self.env,
> File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
> hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\Oke\Desktop\8muses downloader\8muser-master\app.py", line 39, in
> driver = webdriver.Chrome(chrome_driver_path, chrome_options=options)
> File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in **init**
> self.service.start()
> File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
> raise WebDriverException(
> selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

DevTools listening on ws://127.0.0.1:60561/devtools/browser/83abe827-b838-4e10-8ece-1bb8cb4a50a9
Loading Comic...
[0813/115320.353:ERROR:ssl_client_socket_impl.cc(981)] handshake failed; returned -1, SSL error code 1, net_error -100
Comic successfully loaded
Traceback (most recent call last):
  File "C:\Users\Oke\Desktop\8muses downloader\8muser-master\app.py", line 44, in <module>
    soup = BeautifulSoup(album_html,"lxml")
  File "C:\Users\Oke\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

C:\Users\Oke\Desktop\8muses downloader\8muser-master>
